### ISSUE TITLE
Clarify usage of Ideogram in-app (Usage of Ideogram is not clear)

### ISSUE THREAD

**Issue by eljefuri** [cassidyjames/ideogram#11]
When I open the Ideogram application, the usage of the app is basically non-obvious for a number of reasons:

- It doesn't tell me in advance that clicking on any emoji copies it into the clipboard
- It doesn't give any visual confirmation that anything was copied
- It doesn't suggest in any way that it will close the interface after clicking, or what that means
- It gives the appearance of a text field for "testing" emojis at the bottom off the window ("Select an Emoji"), but clicking there only closes it.
- It doesn't explain that an Insert Emoji context menu is now present throughout the OS

**Comment by eljefuri** [comment]
> The app listing in AppCenter is very concise but describes exactly this. Adding extra explanatory UI to describe the single reason the entire app exists feels a bit heavy to me, and would feel condescending. The goal is for Ideogram to be very lightweight visually so that it does not get in the way of your workflow in whatever app you're actually using.

You're assuming a few things here that are probably debatable:

1. That someone read the description rather than simply looking at the screenshot and making an assumption, or worse.
2. That there was little time between the install of the app and running: i.e. that its purpose was clearly remembered.
3. That it was downloaded with specific intentionality; in fact it may have been downloaded quite flippantly the time of a first exploration of AppCenter.

Obviously I agree that it shouldn't be condescending, but _all you need to do_ is change the text in the origin window to "Click an emoji to copy it", or something equivalently/more short.

> > It doesn't give any visual confirmation that anything was copied
> 
> Fair, I'll consider that a feature request.
> 
> > It doesn't suggest in any way that it will close the interface after clicking, or what that means
> 
> This is consistent with the existing OS-wide emoji picker. I think combined with the previous request this would be alleviated.

I agree, it would probably solve that. But I also think you should change the copy slightly per the above, to remind users of the purpose of the app.

> The origin window is not styled like a text input, and testing an emoji would simply result in showing the exact same character that was just selected in the popover. Further, selecting an emoji inserts it into any focused text field, just like the built-in emoji picker. Opening Ideogram should be fast enough that this is a very lightweight and low-cost action, and the user should be able to reopen the app quickly if that's not what they wanted. See #9

Fair enough.

> > It doesn't explain that an Insert Emoji context menu is now present throughout the OS
> 
> This has nothing to do with Ideogram, that's a feature in elementary OS Juno, implemented in GTK itself.

Got it. I didn't know of the existence of that context menu and thought that I had somehow enabled it with the install of Ideogram. Good to know!

Finally, yes I'll avoid opening multi-issues like this in the future, sorry about that!

**Comment by cassidyjames** [comment]
I just realized one possible weirdness of this; it's designed to paste into any text field, and copying to the clipboard is actually a byproduct of that (it copies it and then immediately pastes into any focused text entry). If no text entry is focused, it will seemingly only copy the emoji because the paste goes unnoticed.

Unfortunately there's no way to detect if the user has a non-native text input focused, so Ideogram can't know whether or not the paste was successful.
