### ISSUE TITLE
Search is not especially comprehensive

### ISSUE THREAD

**Issue by eljefuri** [cassidyjames/ideogram#12]
It seems that there is not enough metadata on each emoji to make the search field really useful. For example, typing "sad" produces a single emoji, while "happy" produces none. Perhaps you could ask the Emojipedia folks if you could borrow their database[1]. [Here](https://emojipedia.org/search/?q=sad) is an example of a search on Emojipedia for "sad", and [here](https://emojipedia.org/search/?q=happy) is an example of a similar search for "happy". Adding to the complexity, you will of course need to offer such a database for every language that Elementary supports.

[1] _To be clear, I would not want to see this become an online-only tool, hence why I said "borrow" rather than "use". And of course we may be better off creating a generalized, endlessly localizable database of Emoji metadata that anyone can use._

**Comment by cassidyjames** [comment]
Ideogram does not implement the emoji picker, it simply uses the one embedded in GTK. This would need to be solved in GTK itself. It looks like GTK master does have some improvements here but I'm unsure how extensive they are.
