### ISSUE TITLE
Missing: 🆕 emoji

### ISSUE THREAD

**Issue by igalic** [cassidyjames/ideogram#16]
Typing `new` shows

> ### Travel
>
> 🌑 🌚 
>
> ### Objects
>
> 📰 🗞 

but 🆕 is missing.

**Comment by cassidyjames** [comment]
Thanks for filing an issue! However—as noted in the [README](https://github.com/cassidyjames/ideogram/#about-the-emoji-picker)—Ideogram has no control over the actual emoji presented. That is entirely up to [GTK](https://gitlab.gnome.org/GNOME/gtk) and the OS:

>The emoji picker that Ideogram uses is provided by [GTK](https://gitlab.gnome.org/GNOME/gtk). **Anything about the emoji picker itself is outside of the scope of this app, and outside of my control. For example, the emojis presented**, the scrolling performance, the search, the keywords, etc. If you have issues with the emoji picker, please file them with GTK so it can be improved not just for Ideogram, but for all apps and platforms that use GTK.

**Comment by igalic** [comment]
honestly, the more i think about this particular issue, the more i think it's fontconfig that's to blame

**Comment by cassidyjames** [comment]
@igalic the emoji shows up if the browse to it, so I think it's just the GTK emoji picker's lackluster keywords in 3.22.
