### ISSUE TITLE
Cannot insert emoji on webpages in chrome

### ISSUE THREAD

**Issue by biswaz** [cassidyjames/ideogram#22]
Tried inserting on text boxes in web pages using chrome, but failed. 
Works fine on firefox, issues seem to be affecting only chrome. Have not tested on chromium. 

I can still insert to the search bar (Omnibox) of chrome.

```
Distributor ID:	elementary
Description:	elementary OS 5.0 Juno
Release:	5.0
Codename:	juno
Linux biswaz-HP-Notebook 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

ideogram version: 1.2.2
```

**Comment by cassidyjames** [comment]
@biswaz works fine here in Chromium. I don't have Google Chrome to test, but it should be exactly the same. Is it possible the website you're trying to insert into has disabled pasting, or only allows certain characters?

**Comment by cassidyjames** [comment]
I can't reproduce this here. Feel free to add additional details if it's still reproducible, and we can re-open it.
