### ISSUE TITLE
Fake window is visible when GTK_CSD isn't set

### ISSUE THREAD

**Issue by worldofpeace** [cassidyjames/ideogram#26]
I've attempted to package this application for NixOS and when I launch it
the application appears like this:

![Screenshot from 2019-08-04 07 32 19](https://user-images.githubusercontent.com/28888242/62423034-17a5e180-b68a-11e9-93b0-de9a2e63c701.png)

Un-captured in this screenshot are the window decorations.

Is this expected? I was under the impression this was going to appear in the same concept as 
* https://github.com/elementary/shortcut-overlay

**Comment by cassidyjames** [comment]
This probably depends on the window manager and its version… I have only tested Ideogram on elementary OS.

**Comment by worldofpeace** [comment]
> This probably depends on the window manager and its version…

I maintain Pantheon in nixpkgs and this was observed within it.
Window manager is Gala 0.3.1.

>  The Shortcut Overlay is not drawing a fake window or anything, it’s just a dialog-styled window. But I need to draw a fake window to give the popover somewhere to go, because GTK does not support showing popovers outside of windows.

I see how that is needed here specifically. Thanks for explaining.

>  I'm not sure why the styling to hide the window is not working on NixOS.

Can you link to where the actual styling is happening within the source?

**Comment by cassidyjames** [comment]
Styling:

https://github.com/cassidyjames/ideogram/blob/master/data/Application.css

What version of Mutter are you building against? Do other windows (specifically: actual dialogs) show a titlebar when they shouldn't? If I recall correctly, there's a specific environment variable set in elementary OS for GTK that changes how titlebars work.

Oh also, what version of GTK are you using?

**Comment by worldofpeace** [comment]
GTK3: 3.24.10
GLib: 2.60.4
Mutter: 3.28.4 with [backported patches](https://github.com/NixOS/nixpkgs/blob/cf9dca23969400e4a8d31e5e37186c39fd99b12f/pkgs/desktops/gnome-3/core/mutter/3.28.nix#L27)
GSD: 3.30.2


nixpkgs on master currently has GNOME 3.32, and we've kept around older versions of mutter
and patched gnome-settings-daemon to support Pantheon (ubuntu and pantheon's patches).

>  Do other windows (specifically: actual dialogs) show a titlebar when they shouldn't? If I recall correctly, there's a specific environment variable set in elementary OS for GTK that changes how titlebars work.

I recall this discussion also and believed it wasn't issue we were having.
Think it was https://github.com/elementary/default-settings/blob/master/profile.d/gtk-csd.sh.

And after running the executable with 
`GTK_CSD=1 com.github.cassidyjames.ideogram` 
this window appears appropriately :fireworks:

I guess you should document this here and we'll do this for Pantheon in NixOS.

**Comment by cassidyjames** [comment]
I can add that to the .desktop file, maybe. I'll take a look.
