### ISSUE TITLE
Distribute as Flatpak for AppCenter

### ISSUE THREAD

**Issue by LeandroStanger** [cassidyjames/ideogram#4]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by cassidyjames** [comment]
Ideogram is made for and distributed via elementary OS.

**Comment by ChildishGiant** [comment]
Any chance this'll be reconsidered? :wink:

**Comment by cassidyjames** [comment]
I'll see if it can work in a Flatpak for AppCenter, yes!
