### ISSUE TITLE
Pressing Enter should select the first emoji

### ISSUE THREAD

**Issue by m93a** [cassidyjames/ideogram#40]
## Steps
1. Press Meta+E
2. Type “think”
3. Press Enter

## What should happen
The “thinking face” emoji should get pasted… 🤔️

## What actually happens
Nothing. I have to press Down before Enter to paste the emoji.

**Comment by cassidyjames** [comment]
The emoji picker is provided by (and internal to) GTK; I can't change its behavior. This would need to be solved in GTK itself.
