### ISSUE TITLE
Change default shortcut to "Super" + "."

### ISSUE THREAD

**Issue by marbetschar** [cassidyjames/ideogram#41]
Would be great to have the default shortcut for Ideogram changed to `Super` + `.`, because that's the way it works on Windows. Since `Super` + `E` becomes available then, one might use it to open a new File Manager window - which corresponds too to the shortcut used for this on Windows.

**Comment by m93a** [comment]
I think `Super+E` is fine. It's the most intuitive for everybody who's not comming from Windows. I'd put more stress on fixing #2, then you'd be able to change the shortcut however you like.

**Comment by marbetschar** [comment]
@m93 you're already able to change the shortcut in Hera's **System Settings > Keyboard > Shortcuts > Custom**. That said, I'd argue #2 is "fixed" already ;)
