### ISSUE TITLE
Show Name of Emoji as Tooltip

### ISSUE THREAD

**Issue by xd1936** [cassidyjames/ideogram#5]
Great program, just purchased! Should be a core OS feature :smile:

It would be awesome if there was some way to know the names of the Emoji... perhaps as a tooltip? :thinking:
If I open the app and type "shrug", there's know way to know the difference between "person shrugging" and "female shrugging", for example.

**Comment by cassidyjames** [comment]
The contents of the popover shown is provided directly by GTK and I do not have control over it. That issue would need to be raised at https://gitlab.gnome.org/GNOME/gtk
