### ISSUE TITLE
Feature request: Alt/Hover Text

### ISSUE THREAD

**Issue by vjxyz** [cassidyjames/ideogram#54]
It would be nice if each emoji in Ideogram showed an alt text, so that when I hover over it with my mouse, I can see the proper name.  For example, it took me a while to figure out that 🎃️ = :jack: instead of :pumpkin:  Thanks!  😺️

**Comment by cassidyjames** [comment]
As mentioned in the README,

>The emoji picker that Ideogram uses is designed and provided by [GTK](https://gitlab.gnome.org/GNOME/gtk). **Anything about the emoji picker itself is outside of the scope of this app, and outside of my control.** For example, the Unicode emoji that are presented, the font used, the scrolling performance, the search, the keywords, etc. If you have issues with the emoji picker, please file them with GTK so it can be improved not just for Ideogram, but for all apps and platforms that use GTK.

Unfortunately [my request for this exact thing](https://gitlab.gnome.org/GNOME/gtk/-/issues/910) was dismissed mostly out of hand.
