### ISSUE TITLE
Not available in AppCenter

### ISSUE THREAD

**Issue by JohnDumpling** [cassidyjames/ideogram#59]
After the release of Elementary OS 6, Ideogram (and many other apps developed by you) are no longer available in the AppCenter. Could you please update your apps for EOS 6 (when you have time, no pressure of course)? Thank you if you do.

**Comment by waldyrious** [comment]
Duplicate of #4?

**Comment by JohnDumpling** [comment]
Oopsie, I didn't notice, as I was reporting like 50 issues with missing apps, bugs and feature requests in elementary today :D I will close this.

**Comment by cassidyjames** [comment]
@JohnDumpling no worries, thanks for your reaching out!
