### ISSUE TITLE
Support for current emoji (up to 11.0)

### ISSUE THREAD

**Issue by lfuelling** [cassidyjames/ideogram#6]
Hi,

it would be nice if the app could support all the currently available emojis.
- Current stable: https://emojipedia.org/unicode-11.0/
- Current draft https://emojipedia.org/unicode-12.0/

**Edit:** it seems like the application uses the GTK Emoji chooser. Enabling support for newer Emoji would likely require to use a custom one.

**Comment by cassidyjames** [comment]
I have no interest in providing my own emoji picker and plan to continue using the GTK picker. Supporting more emoji would need to be raised at  https://gitlab.gnome.org/GNOME/gtk
