### ISSUE TITLE
Visualize shortcuts on rollover

### ISSUE THREAD

**Issue by wout** [cassidyjames/ideogram#7]
I love this app! Something I missed while I was still on Pop!_OS.

What would make this app even better is visualizing the shortcuts/keywords underneath the emoticons on hover. Very subtle, something like this (big):

![ideogram-hover-label](https://user-images.githubusercontent.com/107324/47724023-1a385e00-dc56-11e8-8345-02d7a06f33e4.png)

**Comment by cassidyjames** [comment]
Duplicate of #5
