### ISSUE TITLE
Libraries for Compatibility

### ISSUE THREAD

**Issue by btd1337** [cassidyjames/ideogram#8]
Hey Cassidy, would you know if your program needs any special libraries to work?

This is Ideogram running on Gnome 3.30.

![captura de tela de 2018-11-09 16-08-56](https://user-images.githubusercontent.com/11943860/48280340-72cbe000-e43a-11e8-839e-77f1872436ad.png)

**Comment by cassidyjames** [comment]
@btd1337 I have no idea. It should just require GTK >= 3.22 and the elementary stylesheet. It might require X if you're running on Wayland, but your emoji picker looks super broken, even though that's just provided by GTK itself.

**Comment by cassidyjames** [comment]
@btd1337 what do other GTK emoji pickers look like? I.e. open a native GTK app and hit <kbd>Ctrl</kbd>+<kbd>;</kbd>

**Comment by btd1337** [comment]
It didn't work correctly. I can't select emojis and after a search it doesn't return to the initial state without my ending the application. I too can't to select any categories.

![captura de tela de 2018-11-14 23-40-32](https://user-images.githubusercontent.com/11943860/48524370-313a9b00-e867-11e8-9b49-ab178899d58d.png)

![captura de tela de 2018-11-14 23-40-32](https://user-images.githubusercontent.com/11943860/48524378-3697e580-e867-11e8-8f84-1678a4af4fb8.png)

**Comment by cassidyjames** [comment]
It appears your global GTK emoji picker is somehow super broken. So this is not specific to Ideogram.
